language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install

script: php vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

notifications:
  webhooks:
    urls: 
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true

after_script: sh -c " if [ -f ./build/logs/clover.xml ]; then php vendor/bin/coveralls; fi"
